### ISSUE TITLE
Bump Gradle plugin version

### ISSUE THREAD

**Issue by guidezpl** [microsoft/flutter-dualscreen#4]
Updating to latest Gradle versions is not possible if depending on the package because it does not satisfy version requirements

 ```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':dual_screen' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10
```

I suspect both `classpath 'com.android.tools.build:gradle:4.1.3'` and  `ext.kotlin_version = '1.5.10'` need to be bumped.

**Comment by andreidiaconu** [comment]
Will have a look and get back to you.

**Comment by guidezpl** [comment]
Related: https://github.com/flutter/flutter/issues/125181

**Comment by andreidiaconu** [comment]
Opened PR #3, which should be quick to close. Also upgraded to agp 7, even though it did not seem necessary.

**Comment by guidezpl** [comment]
Thanks! Can you please publish `1.0.4`?

**Comment by andreidiaconu** [comment]
The publish action uses Flutter master and two tests are failing. Investigating.

**Comment by andreidiaconu** [comment]
Sorry for the delay - 1.0.4 is up and the next updates should go through faster if we need more changes.

**Comment by guidezpl** [comment]
Great, thank you
